---
- name: Verificar KB instalado
  hosts: windows-servers

  tasks:
  - name: Verificar KB especifico
    win_updates: 
      category_names: '{{ update_category }}'
      state: searched
      whitelist: '{{ kb_id }}'

